services:
  postgres:
    image: postgres:15-alpine
    container_name: bricklink_postgres
    environment:
      POSTGRES_DB: bricklink
      POSTGRES_USER: bricklink_user
      POSTGRES_PASSWORD: bricklink_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bricklink_user -d bricklink"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: eqalpha/keydb:latest
    container_name: bricklink_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: >
      keydb-server
      --maxmemory 2gb
      --maxmemory-policy noeviction
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --stop-writes-on-bgsave-error yes
      --rdbcompression yes
      --rdbchecksum yes
      --dir /data
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    mem_limit: 3gb
    memswap_limit: 3gb

  # bricklink-parser:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: bricklink-parser
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - DATABASE_HOST=postgres
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
    
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: bricklink_network
