services:
  postgres:
    image: postgres:15-alpine
    container_name: bricklink_postgres
    environment:
      POSTGRES_DB: bricklink
      POSTGRES_USER: bricklink_user
      POSTGRES_PASSWORD: bricklink_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bricklink_user -d bricklink"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: eqalpha/keydb:latest
    container_name: bricklink_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  bricklink-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bricklink-parser
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped
    vo
    
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: bricklink_network
